/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_imgproc_Imgproc */

#ifndef _Included_org_visp_imgproc_Imgproc
#define _Included_org_visp_imgproc_Imgproc
#ifdef __cplusplus
extern "C" {
#endif
#undef org_visp_imgproc_Imgproc_IPL_BORDER_CONSTANT
#define org_visp_imgproc_Imgproc_IPL_BORDER_CONSTANT 0L
#undef org_visp_imgproc_Imgproc_IPL_BORDER_REPLICATE
#define org_visp_imgproc_Imgproc_IPL_BORDER_REPLICATE 1L
#undef org_visp_imgproc_Imgproc_IPL_BORDER_REFLECT
#define org_visp_imgproc_Imgproc_IPL_BORDER_REFLECT 2L
#undef org_visp_imgproc_Imgproc_IPL_BORDER_WRAP
#define org_visp_imgproc_Imgproc_IPL_BORDER_WRAP 3L
#undef org_visp_imgproc_Imgproc_IPL_BORDER_REFLECT_101
#define org_visp_imgproc_Imgproc_IPL_BORDER_REFLECT_101 4L
#undef org_visp_imgproc_Imgproc_IPL_BORDER_TRANSPARENT
#define org_visp_imgproc_Imgproc_IPL_BORDER_TRANSPARENT 5L
#undef org_visp_imgproc_Imgproc_LINE_AA
#define org_visp_imgproc_Imgproc_LINE_AA 16L
#undef org_visp_imgproc_Imgproc_LINE_8
#define org_visp_imgproc_Imgproc_LINE_8 8L
#undef org_visp_imgproc_Imgproc_LINE_4
#define org_visp_imgproc_Imgproc_LINE_4 4L
#undef org_visp_imgproc_Imgproc_RETINEX_UNIFORM
#define org_visp_imgproc_Imgproc_RETINEX_UNIFORM 0L
#undef org_visp_imgproc_Imgproc_RETINEX_LOW
#define org_visp_imgproc_Imgproc_RETINEX_LOW 1L
#undef org_visp_imgproc_Imgproc_RETINEX_HIGH
#define org_visp_imgproc_Imgproc_RETINEX_HIGH 2L
#undef org_visp_imgproc_Imgproc_AUTO_THRESHOLD_HUANG
#define org_visp_imgproc_Imgproc_AUTO_THRESHOLD_HUANG 0L
#undef org_visp_imgproc_Imgproc_AUTO_THRESHOLD_INTERMODES
#define org_visp_imgproc_Imgproc_AUTO_THRESHOLD_INTERMODES 1L
#undef org_visp_imgproc_Imgproc_AUTO_THRESHOLD_ISODATA
#define org_visp_imgproc_Imgproc_AUTO_THRESHOLD_ISODATA 2L
#undef org_visp_imgproc_Imgproc_AUTO_THRESHOLD_MEAN
#define org_visp_imgproc_Imgproc_AUTO_THRESHOLD_MEAN 3L
#undef org_visp_imgproc_Imgproc_AUTO_THRESHOLD_OTSU
#define org_visp_imgproc_Imgproc_AUTO_THRESHOLD_OTSU 4L
#undef org_visp_imgproc_Imgproc_AUTO_THRESHOLD_TRIANGLE
#define org_visp_imgproc_Imgproc_AUTO_THRESHOLD_TRIANGLE 5L
/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    adjust_0
 * Signature: (JJDD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_adjust_10
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    adjust_1
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_adjust_11
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    adjust_2
 * Signature: (JJDD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_adjust_12
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    adjust_3
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_adjust_13
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    clahe_0
 * Signature: (JJIIFZ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_clahe_10
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat, jboolean);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    clahe_1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_clahe_11
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    clahe_2
 * Signature: (JJIIFZ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_clahe_12
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat, jboolean);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    clahe_3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_clahe_13
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    equalizeHistogram_0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_equalizeHistogram_10
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    equalizeHistogram_1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_equalizeHistogram_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    equalizeHistogram_2
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_equalizeHistogram_12
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    equalizeHistogram_3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_equalizeHistogram_13
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    equalizeHistogram_4
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_equalizeHistogram_14
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    equalizeHistogram_5
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_equalizeHistogram_15
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    fillHoles_0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_fillHoles_10
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    fillHoles_2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_fillHoles_12
  (JNIEnv *, jclass);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    gammaCorrection_0
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_gammaCorrection_10
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    gammaCorrection_1
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_gammaCorrection_11
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    gammaCorrection_2
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_gammaCorrection_12
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    gammaCorrection_3
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_gammaCorrection_13
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    reconstruct_0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_reconstruct_10
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    reconstruct_2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_reconstruct_12
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    retinex_0
 * Signature: (JJIIIDI)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_retinex_10
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jdouble, jint);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    retinex_1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_retinex_11
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    retinex_2
 * Signature: (JIIIDI)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_retinex_12
  (JNIEnv *, jclass, jlong, jint, jint, jint, jdouble, jint);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    retinex_3
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_retinex_13
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    stretchContrast_0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_stretchContrast_10
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    stretchContrast_1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_stretchContrast_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    stretchContrast_2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_stretchContrast_12
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    stretchContrast_3
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_stretchContrast_13
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    stretchContrastHSV_0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_stretchContrastHSV_10
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    stretchContrastHSV_1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_stretchContrastHSV_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_0
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_10
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_11
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_2
 * Signature: (JJID)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_12
  (JNIEnv *, jclass, jlong, jlong, jint, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_13
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_4
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_14
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_5
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_15
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_6
 * Signature: (JJID)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_16
  (JNIEnv *, jclass, jlong, jlong, jint, jdouble);

/*
 * Class:     org_visp_imgproc_Imgproc
 * Method:    unsharpMask_7
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_Imgproc_unsharpMask_17
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
