/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_core_VpArray2D */

#ifndef _Included_org_visp_core_VpArray2D
#define _Included_org_visp_core_VpArray2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_VpArray2D
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpArray2D_n_1VpArray2D__
  (JNIEnv *, jclass);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_VpArray2D
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpArray2D_n_1VpArray2D__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_VpArray2D
 * Signature: (IID)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpArray2D_n_1VpArray2D__IID
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_cols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpArray2D_n_1cols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpArray2D_n_1rows
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
