/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_core_VpArray2D */

#ifndef _Included_org_visp_core_VpArray2D
#define _Included_org_visp_core_VpArray2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_VpArray2D
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpArray2D_n_1VpArray2D__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_VpArray2D
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpArray2D_n_1VpArray2D__Ljava_lang_String_2II
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_VpArray2D
 * Signature: (Ljava/lang/String;IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpArray2D_n_1VpArray2D__Ljava_lang_String_2IILjava_lang_String_2
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_cols
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpArray2D_n_1cols
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_visp_core_VpArray2D
 * Method:    n_rows
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpArray2D_n_1rows
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
