/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_gui_VpDisplayOpenCV */

#ifndef _Included_org_visp_gui_VpDisplayOpenCV
#define _Included_org_visp_gui_VpDisplayOpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_0
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_10
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_1
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_11
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_2
 * Signature: (JIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_12
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_3
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_13
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_4
 * Signature: (JIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_14
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_15
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    VpDisplayOpenCV_6
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_visp_gui_VpDisplayOpenCV_VpDisplayOpenCV_16
  (JNIEnv *, jclass);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    getScreenHeight_0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_gui_VpDisplayOpenCV_getScreenHeight_10
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    getScreenWidth_0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_gui_VpDisplayOpenCV_getScreenWidth_10
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    getImage_0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_getImage_10
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    init_0
 * Signature: (JIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_init_10
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jstring);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    init_1
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_init_11
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    init_2
 * Signature: (JJIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_init_12
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jstring);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    init_3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_init_13
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    init_4
 * Signature: (JJIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_init_14
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jstring);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    init_5
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_init_15
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_gui_VpDisplayOpenCV
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_gui_VpDisplayOpenCV_delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
