/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_core_VpImageRGBa */

#ifndef _Included_org_visp_core_VpImageRGBa
#define _Included_org_visp_core_VpImageRGBa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_VpImageRGBa
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageRGBa_n_1VpImageRGBa__
  (JNIEnv *, jclass);

/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_VpImageRGBa
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageRGBa_n_1VpImageRGBa__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_VpImageRGBa
 * Signature: (IICCCC)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageRGBa_n_1VpImageRGBa__IICCCC
  (JNIEnv *, jclass, jint, jint, jchar, jchar, jchar, jchar);

/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_VpImageRGBa
 * Signature: ([BIIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageRGBa_n_1VpImageRGBa___3BIIZ
  (JNIEnv *, jclass, jbyteArray, jint, jint, jboolean);

/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_cols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpImageRGBa_n_1cols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpImageRGBa_n_1rows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpImageRGBa
 * Method:    n_dump
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visp_core_VpImageRGBa_n_1dump
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
