/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_io_VpImageIo */

#ifndef _Included_org_visp_io_VpImageIo
#define _Included_org_visp_io_VpImageIo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_io_VpImageIo
 * Method:    read_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_read_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    read_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_read_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readJPEG_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readJPEG_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readJPEG_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readJPEG_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readPGM_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readPGM_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readPGM_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readPGM_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readPNG_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readPNG_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readPNG_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readPNG_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readPPM_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readPPM_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    readPPM_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_readPPM_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    write_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_write_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    write_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_write_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writeJPEG_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writeJPEG_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writeJPEG_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writeJPEG_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writePGM_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writePGM_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writePGM_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writePGM_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writePNG_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writePNG_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writePNG_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writePNG_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writePPM_0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writePPM_10
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    writePPM_1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_writePPM_11
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_visp_io_VpImageIo
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_io_VpImageIo_delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
