/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_core_VpImageUChar */

#ifndef _Included_org_visp_core_VpImageUChar
#define _Included_org_visp_core_VpImageUChar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_VpImageUChar
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageUChar_n_1VpImageUChar__
  (JNIEnv *, jclass);

/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_VpImageUChar
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageUChar_n_1VpImageUChar__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_VpImageUChar
 * Signature: (IIB)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageUChar_n_1VpImageUChar__IIB
  (JNIEnv *, jclass, jint, jint, jbyte);

/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_VpImageUChar
 * Signature: ([BIIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImageUChar_n_1VpImageUChar___3BIIZ
  (JNIEnv *, jclass, jbyteArray, jint, jint, jboolean);

/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_cols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpImageUChar_n_1cols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpImageUChar_n_1rows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpImageUChar
 * Method:    n_dump
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visp_core_VpImageUChar_n_1dump
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
