/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_imgproc_VpImgproc */

#ifndef _Included_org_visp_imgproc_VpImgproc
#define _Included_org_visp_imgproc_VpImgproc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_imgproc_VpImgproc
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_visp_imgproc_VpImgproc_delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
