/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_core_VpImage */

#ifndef _Included_org_visp_core_VpImage
#define _Included_org_visp_core_VpImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_core_VpImage
 * Method:    n_VpImage
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImage_n_1VpImage__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_visp_core_VpImage
 * Method:    n_VpImage
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImage_n_1VpImage__Ljava_lang_String_2II
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_visp_core_VpImage
 * Method:    n_VpImage
 * Signature: (Ljava/lang/String;IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImage_n_1VpImage__Ljava_lang_String_2IILjava_lang_String_2
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     org_visp_core_VpImage
 * Method:    n_VpImage
 * Signature: (Ljava/lang/String;[BIIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpImage_n_1VpImage__Ljava_lang_String_2_3BIIZ
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jint, jboolean);

/*
 * Class:     org_visp_core_VpImage
 * Method:    n_cols
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpImage_n_1cols
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_visp_core_VpImage
 * Method:    n_rows
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpImage_n_1rows
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_visp_core_VpImage
 * Method:    n_dump
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visp_core_VpImage_n_1dump
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
