/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_visp_core_VpMatrix */

#ifndef _Included_org_visp_core_VpMatrix
#define _Included_org_visp_core_VpMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_vpMatrix
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpMatrix_n_1vpMatrix__
  (JNIEnv *, jclass);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_vpMatrix
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpMatrix_n_1vpMatrix__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_vpMatrix
 * Signature: (IID)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpMatrix_n_1vpMatrix__IID
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_vpMatrix
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_visp_core_VpMatrix_n_1vpMatrix__JIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_cols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpMatrix_n_1cols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_visp_core_VpMatrix_n_1rows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_transpose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_visp_core_VpMatrix_n_1transpose
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_visp_core_VpMatrix
 * Method:    n_dump
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_visp_core_VpMatrix_n_1dump
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
